text_composition_strategy legacy
font_size           12.5
adjust_line_height  0
# macos_thicken_font 1

# text_composition_strategy 0.01 10
# text_fg_override_threshold 2


font_family         JetBrains Mono
bold_font           JetBrains Mono Bold
italic_font         JetBrains Mono Italic
bold_italic_font    JetBrains Mono Bold Italic
font_features       JetBrainsMono-Regular       -calt +ss01 +zero
font_features       JetBrainsMono-Bold          -calt +ss01 +zero
font_features       JetBrainsMono-Italic        -calt +ss01 +zero
font_features       JetBrainsMono-BoldItalic    -calt +ss01 +zero

editor                   .
cursor_blink_interval    -1
cursor_trail             0

repaint_delay            30
sync_to_monitor          yes

tab_bar_style            powerline
background               #000000
background_opacity       0.95

enable_audio_bell        no
confirm_os_window_close  0

# include themes/adwaita-darker.conf
# include dark-pastel.conf
include ir-black.conf
