# font_size           11.5
# adjust_line_height  110%
# macos_thicken_font 1

# text_composition_strategy 0.01 10
# text_fg_override_threshold 2


font_family         JetBrains Mono
bold_font           JetBrains Mono Bold
italic_font         JetBrains Mono Italic
bold_italic_font    JetBrains Mono Bold Italic
font_features       JetBrainsMono-Regular       -calt +ss01 +zero
font_features       JetBrainsMono-Bold          -calt +ss01 +zero
font_features       JetBrainsMono-Italic        -calt +ss01 +zero
font_features       JetBrainsMono-BoldItalic    -calt +ss01 +zero

cursor_blink_interval    -1
cursor_trail             1

tab_bar_style            powerline
background               #000000
background_opacity       0.9

enable_audio_bell        no
confirm_os_window_close  0

