gui:
  theme:
    activeBorderColor:
      - white
    inactiveBorderColor:
      - black
    defaultFgColor:
      - default
    selectedLineBgColor:
      - black
  commitLength:
    show: true
  screenMode: half # normal | half | full
  border: single
  expandFocusedSidePanel: true
  sidePanelWidth: 0.25
  expandedSidePanelWeight: 5
  commitAuthorShortLength: 0
  commitAuthorLongLength: 0
  shawRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showListFooter: false
git:
  pagers:
    - pager: delta --paging=never --diff-so-fancy --detect-dark-light=always
      colorArg: always
update:
  autoUpdate: false
  checkForUpdates: false
