# vim:fileencoding=utf-8:ft=conf

#
# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀
#
env = GDK_BACKEND,wayland,x11,*

env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = SDL_VIDEODRIVER,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = WLR_DRM_NO_ATOMIC,1

# Cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Phinger Cursors (light)
env = XCURSOR_THEME,Phinger Cursors (light)


#
# ▄▀█ █░█ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀█ ▀█▀ █▀
# █▀█ █▄█ ░█░ █▄█ ▄█ ░█░ █▀█ █▀▄ ░█░ ▄█
#
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" &
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Colloid-Dark"
exec-once = hyprctl setcursor "Phinger Cursors (light)" 24 &
exec-once = systemctl --user start ulauncher & # Auto-start ulauncher
exec-once = swww-daemon & swaync & waybar &
exec-once = wl-paste --type text --watch cliphist store & # Stores only text data
exec-once = wl-paste --type image --watch cliphist store & # Stores only image data
