# vim:fileencoding=utf-8:ft=conf

# Left to configure: group window-rule

$terminal = ghostty
$fileManager = thunar
$menu = ulauncher-toggle
# tofi-drun

# monitor=,preferred,auto,auto
monitor = HDMI-A-1,1366x768,0x0,1

misc {
  enable_swallow = true
  swallow_regex = ^(Alacritty|kitty)$

  force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background.
}

# INFO:
# 🅺🅴🆈🅱🅸🅽🅳🅸🅽🅶🆂   keybindings
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/inputs.conf
source = ~/.config/hypr/windowrules.conf
