general {
  gaps_in = 3
  gaps_out = 5

  border_size = 0

  # col.active_border = rgb(48484A) rgb(636366) 90deg
  col.active_border = rgba(FFFFFF4D)
  col.inactive_border =  rgba(FFFFFF0D)

  # Set to true enable resizing windows by clicking and dragging on borders and gaps
  resize_on_border = false

  allow_tearing = false

  layout = dwindle
}

decoration {
  rounding = 6
  rounding_power = 6
  active_opacity = 1.0
  inactive_opacity = 0.9

  shadow {
    enabled = false

    # range = 10               # Slightly larger range for a softer shadow
    # render_power = 3         # Lower power for a more subtle falloff
    # sharp = false            # Soft shadow, not sharp
    # ignore_window = true     # Shadow only around the window, not behind it
    # color = rgba(0000004D)   # Light, subtle shadow (dark but with low opacity)
    # color_inactive = rgba(00000000)  # No shadow for inactive windows
    # offset = 0, 1          # Slight vertical offset, typical of macOS
    # scale = 0.9              # Slight scale for a softer, more natural shadow

    # range = 20
    # render_power = 3
    # color= rgba(0000004D)
    # color_inactive = rgba(00000000)

    # Default
    # range = 4
    # render_power = 3
    # color = rgba(1a1a1aee)
  }

  blur {
    enabled = true
    size = 5
    passes = 4
    new_optimizations = true
    ignore_opacity = true

    contrast = 2
    # brightness = 1.3 # 2

    # floating windows will ignore tiled windows in their blur
    xray = false

    # blur popups (e.g. right-click menus)
    popups = false
  }
}

animations {
  enabled = true

  bezier = md3_decel, 0.05, 0.7, 0.1, 1
  bezier = easeOutQuint,0.23,1,0.32,1
  bezier = easeInOutCubic,0.65,0.05,0.36,1
  bezier = linear,0,0,1,1
  bezier = almostLinear,0.5,0.5,0.75,1.0
  bezier = quick,0.15,0,0.1,1

  animation = global, 1, 10, default
  animation = border, 1, 5.39, easeOutQuint
  animation = borderangle, 1, 100, linear, loop
  animation = windows, 1, 4.79, easeOutQuint
  animation = windowsIn, 1, 6, md3_decel, slide
  animation = windowsOut, 1,6, md3_decel, slide
  animation = windowsMove, 1,6, md3_decel, slide
  animation = fadeIn, 1, 1.73, almostLinear
  animation = fadeOut, 1, 1.46, almostLinear
  animation = fade, 1, 10, md3_decel
  animation = workspaces, 1, 7, md3_decel,slide
  animation = specialWorkspace, 1, 8, md3_decel, slide
  animation = layers, 1, 3.81, easeOutQuint
  animation = layersIn, 1, 4, easeOutQuint, fade
  animation = layersOut, 1, 1.5, linear, fade
  animation = fadeLayersIn, 1, 1.79, almostLinear
  animation = fadeLayersOut, 1, 1.39, almostLinear
  animation = workspacesIn, 1, 1.21, md3_decel, slide
  animation = workspacesOut, 1, 1.94, md3_decel, slide
}

dwindle {
  pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = true # You probably want this
  default_split_ratio = 1.23
  force_split = 1
}
master {
  new_status = master
}

# render = {
#     explicit_sync = 0
# }
