# monitor=,preferred,auto,auto
# name, resolution, position(x,y), scaling, bitrate
# monitor = DP-1,     1366x768,0x0,    1, bitdepth, 10
# monitor = HDMI-A-1, 1366x768,1366x0, 1, bitdepth, 10

# # open workspaces on the specified monitors:
# workspace = 1,  monitor:DP-1,     default:true
# workspace = 2,  monitor:DP-1,     default:true
# workspace = 3,  monitor:DP-1,     default:true
# workspace = 4,  monitor:DP-1,     default:true
# workspace = 7,  monitor:HDMI-A-1, default:true
# workspace = 8,  monitor:HDMI-A-1, default:true
# workspace = 9,  monitor:HDMI-A-1, default:true
# workspace = 10, monitor:HDMI-A-1, default:true
