local lze = require("plugin-helper")
lze.setup()

require("plugins.colorscheme")
require("plugins.nvim-tree")
require("plugins.startuptime")
require("plugins.mini_nvim")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.formatter")
require("plugins.harpoon")
require("plugins.leap")
require("plugins.snipp")
require("plugins.gsigns")
require("plugins.fexplore")
