[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
padding.x = 12
padding.y = 3
dynamic_padding = true
decorations = "None" # "Full" | "None"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font]
size = 11.0
# SFMono Nerd Font
# JetBrainsMono Nerd Font
# Monaspace Argon Var
# feather
# Material Icons
# Symbols Nerd Font

[font.offset]
x = 0
y = 4

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[font.italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.2

[general]
# Color-theme
# import = ["~/.config/alacritty/themes/nightlify_mod.toml"]
# import = ["~/.config/alacritty/themes/pastel.toml"]
# import = ["~/.config/alacritty/themes/midnight-haze.toml"]
import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]
